[package]
name = "specs-hierarchy"
version = "0.1.0-alpha2"
authors = ["Aceeri <conmcclusk@gmail.com>", "Rhuagh <seamonr@gmail.com>"]
repository = "https://github.com/rustgd/specs-hierarchy.git"
homepage = "https://github.com/rustgd/specs-hierarchy.git"

license = "MIT/Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/specs-hierarchy"
description = "Scene graph type hierarchy abstraction for use with specs"

keywords = ["specs", "scenegraph", "hierarchy"]

[dependencies]
hibitset = "0.5"
specs = { version = "0.11.0-alpha2" }
shred = { version = "0.7.0-alpha4" }
shrev = "0.8"
shred-derive = { version = "0.5.0-alpha1" }
